#!/bin/sh

ulimit -S -c unlimited
echo  "crash-%e-%s-%u-%g-%p-%t" > /proc/sys/kernel/core_pattern
sysctl  kernel.core_pattern="crash-%e-%s-%u-%g-%p-%t" 
# suffix of the core file name
echo  "1" > /proc/sys/kernel/core_uses_pid

CURDIR=$(pwd)
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURDIR
export PATH=$PATH:$CURDIR

ulimit -n 50000
chmod 777 ./cdnsrv
rm -rf ./log
#while [ 1 ]
#do
    ./cdnsrv  $1
#    sleep 10
#done
